Setup Sequelize for mysql database
LombokAcademy/todo-app pull request #15
Opened 2024-01-30 14:40 UTC by CzNime

2024-02-02 03:13 UTC, pahrizal requested changes

2024-02-02 03:13 UTC, pahrizal commented on src/backend/database/connection.js
> +testConnection();
@CzNime  remove these lines

2024-02-02 07:16 UTC, CzNime commented on src/backend/database/connection.js
> +testConnection();
done sir

2024-02-08 16:02 UTC, pahrizal approved these changes
great! 🎉

2024-02-08 16:02 UTC, merged