creating user model
LombokAcademy/todo-app pull request #20
Opened 2024-02-10 13:54 UTC by juhan26

2024-02-13 11:55 UTC, pahrizal requested changes

2024-02-13 11:55 UTC, pahrizal commented on src/backend/database/user.model.js
> +    type: DataTypes.STRING,
@juhan26 the type should be `UUID.V4` and don't forget to set default value to auto generated UUIDV4 by sequelize. [see this example](https://sequelize.org/docs/v7/models/data-types/#built-in-default-values-for-uuid) for more detail.

2024-02-13 12:17 UTC, juhan26 commented on src/backend/database/user.model.js
> +    type: DataTypes.STRING,
ahhh i forgot, i already add it before. but i forgot to add it back.

2024-02-22 04:51 UTC, pahrizal approved these changes

2024-02-22 04:51 UTC, merged