install and setup tailwindcss
LombokAcademy/todo-app pull request #5
Opened 2024-01-23 15:56 UTC by iamCelott

![image](https://github.com/LombokAcademy/todo-app/assets/95129603/33102187-1dca-4fff-b57d-ddfdd76f93e6)
![image](https://github.com/LombokAcademy/todo-app/assets/95129603/30381bd1-5bbd-4cea-8c4c-fed498e3c4d2)

2024-01-23 16:12 UTC, pahrizal requested changes
please made changes accordingly.

2024-01-23 16:12 UTC, pahrizal commented on src/frontend/index.css
remove all unused css style. only the `@tailwind...` in this file

2024-01-23 16:12 UTC, pahrizal commented on package-lock.json
remove this file. use `yarn` for package manager. when installing package, avoid using `npm install`, use `yarn add <package_name>`

2024-01-23 16:39 UTC, iamCelott commented on package-lock.json
sorry sir, did you mean to delete package-lock.json file??

2024-01-23 18:39 UTC, pahrizal commented
Yes, you’re right. Delete package-lock.json. This file generated when you use `npm i …` commandSent from my iPhoneOn 24 Jan 2024, at 12:39 am, iamCelott ***@***.***> wrote:﻿
@iamCelott commented on this pull request.



On package-lock.json:
sorry sir, did you mean to delete package-lock.json file??

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2024-01-24 04:35 UTC, pahrizal approved these changes
Look awesome! You need a review from your one of your team mates to merge this 🎉

2024-01-24 04:37 UTC, pahrizal commented
Please ask @juhan26 for a review

2024-01-24 07:52 UTC, Azissa approved these changes
awesome can

2024-01-24 08:32 UTC, juhan26 commented
> Please ask @juhan26 for a review

already sir, good job @iamCelott 👍🏼

2024-01-24 10:21 UTC, juhan26 approved these changes
good job @iamCelott

2024-01-24 10:24 UTC, merged